spring.application.name=ProveedorService
server.port=8092

catalog.service.base-url=${CATALOG_BASE_URL:http://localhost:8081}
user.service.base-url=${USER_SERVICE_BASE_URL}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=ALWAYS

SECRET.KEY=${SECRET_KEY}
spring.security.user.name=admin
spring.security.user.password=1234

