version: '3.8'
networks:
  fis-network:
    driver: overlay
  reverse_proxy:
    external: true

configs:
  nginx_config:
    file: ./nginx.conf

x-service-defaults: &service-defaults
  networks:
    - fis-network
  env_file:
    - .env
  restart: always

x-microservice-resources: &microservice-resources
  limits:
    cpus: '1'
    memory: 512M
  reservations:
    cpus: '1'
    memory: 256M

x-clamav-resources: &clamav-resources
  limits:
    cpus: '1'
    memory: 1G
  reservations:
    cpus: '0.5'
    memory: 512M

x-microservice: &microservice
  <<: *service-defaults

services:

  auth:
    <<: *microservice
    image: brayan22/fis-project:auth
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  catalogo:
    <<: *microservice
    image: brayan22/fis-project:catalogo
    environment:
      SERVER_PORT: 8081
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  contenido:
    <<: *microservice
    image: brayan22/fis-project:contenido
    environment:
      SERVER_PORT: 8082
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  email:
    <<: *microservice
    image: brayan22/fis-project:email
    environment:
      SERVER_PORT: 8083
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  foro:
    <<: *microservice
    image: brayan22/fis-project:foro
    environment:
      SERVER_PORT: 8085
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  geo:
    <<: *microservice
    image: brayan22/fis-project:geo
    environment:
      SERVER_PORT: 8086
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  multimedia:
    <<: *microservice
    image: brayan22/fis-project:multimedia
    environment:
      SERVER_PORT: 8089
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  usuario:
    <<: *microservice
    image: brayan22/fis-project:usuario
    environment:
      SERVER_PORT: 8093
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  vehiculo:
    <<: *microservice
    image: brayan22/fis-project:vehiculo
    environment:
      SERVER_PORT: 8094
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      HTTP_BASIC_USER: ${HTTP_BASIC_USER}
      HTTP_BASIC_PASSWORD: ${HTTP_BASIC_PASSWORD}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources: *microservice-resources
  nginx:
    image: nginx:latest
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    <<: *service-defaults
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=reverse_proxy"
        - "traefik.http.routers.fis-project.entrypoints=websecure"
        - "traefik.http.routers.fis-project.tls.certresolver=production"
        - "traefik.http.routers.fis-project.tls=true"
        - "traefik.http.routers.fis-project.rule=Host(`rolapetapp.glud.org`)"
        - "traefik.http.routers.fis-project.service=fis-project"
        - "traefik.http.services.fis-project.loadbalancer.server.port=80"
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - reverse_proxy
      - fis-network