spring.application.name=contenido

server.port=8082


# === CONFIGURACIÓN DE BASE DE DATOS ===
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# metricas
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true