# ==================================
# CONFIGURACI�N DEL SERVIDOR
# ==================================
server.port=8088
spring.application.name=moderacion-service


# metricas
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true